name: build kernel

on:
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检查储存库
        uses: actions/checkout@v4

      - name: 安装依赖
        run: |
          sudo apt update && sudo apt-get install -y curl bison flex make binutils dwarves git lld pahole zip perl gcc python3 python-is-python3 bc libssl-dev libelf-dev device-tree-compiler kmod binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi

      - name: 下载llvm
        run: |
          mkdir llvm12 && cd llvm12
          wget -q https://android.googlesource.com/platform//prebuilts/clang/host/linux-x86/+archive/b669748458572622ed716407611633c5415da25c/clang-r416183b.tar.gz
          tar -zxf clang-r416183b.tar.gz
          mv cd ..
          
      - name: 添加KernelSU Next
        run: |
          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s legacy

      - name: 执行build.sh
        run: |
          chmod +x build.sh
          ./build.sh

      - name: 上传AnyKernel3刷机包
        uses: actions/upload-artifact@v4
        with:
         name: kernel-zip
         path: out/kernel.zip
